version: "2"

networks:
  zeebe_network:
    driver: bridge

services:
  zeebe:
    container_name: zeebe_broker
    image: camunda/zeebe:0.26.0
    environment:
      - ZEEBE_LOG_LEVEL=info
    ports:
      - "26500:26500"
      - "9600:9600"
      - "5701:5701"
    volumes:
      - ./zeebe/zeebe-hazelcast-exporter-0.10.0.jar:/usr/local/zeebe/exporters/zeebe-hazelcast-exporter-0.10.0.jar
      - ./zeebe/application.yaml:/usr/local/zeebe/config/application.yaml
    networks:
      - zeebe_network

  monitor:
    container_name: zeebe_monitor
    image: camunda/zeebe-simple-monitor:0.20.0
    environment:
      - zeebe.client.broker.contactPoint=zeebe:26500
      - zeebe.client.worker.hazelcast.connection=zeebe:5701
    volumes:
      - ./monitor/application.yaml:/application.yaml
    ports:
      - "8082:8082"
    depends_on:
      - zeebe
    networks:
      - zeebe_network
  
  zeebe-provision:
    build: ./zeebe-provision
    environment:
      - ZEEBE_ADDRESS=zeebe:26500
    depends_on:
      - zeebe
    networks:
      - zeebe_network

  http-worker:
    container_name: zeebe-http-worker
    image: camunda/zeebe-http-worker:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - zeebe.client.broker.contactPoint=zeebe:26500
    depends_on:
      - zeebe
    networks:
      - zeebe_network

  script-worker:
    container_name: zeebe-script-worker
    image: camunda/zeebe-script-worker:latest
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      - zeebe.client.broker.contactPoint=zeebe:26500
    depends_on:
      - zeebe
    networks:
      - zeebe_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    ports:
      - 9000:9090
    depends_on: 
      - zeebe
    networks:
      - zeebe_network
    labels:
      org.label-schema.group: "monitoring"
      
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on: 
      - zeebe
    networks:
      - zeebe_network

volumes:
  prometheus_data:
  grafana_data:
