{
 "title": "Zeebe Custom",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Stream Processor Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zeebe_stream_processor_events_total"
    }
   ]
  },
  {
   "title": "Element Instance Events",
   "type": "graph",
   "gridPos": { "h": 16, "w": 11, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zeebe_element_instance_events_total"
    }
   ]
  },
  {
   "title": "Job events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "zeebe_job_events_total" }
   ]
  },
  {
   "title": "Exporter events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "zeebe_exporter_events_total" }
   ]
  }
 ]
}